# Soccer Visualizer Configuration
# Minimal configuration with clear separation of concerns

# Data settings
data:
  input_dir: "tracking_data/data/"
  output_dir: "visualizations"
  split: "test"  # Options: train, valid, test

# Event selection
event:
  type: "Pass"  # Event type to visualize
  index: 0  # Which occurrence to visualize

# Visualization settings
visualization:
  # Frame settings
  frame:
    start: 0  # Starting frame
    end: -1  # Ending frame (-1 for all frames)
    specific: null  # Single frame to visualize (null for animation)
  
  # Field appearance
  field:
    length: 105.0
    width: 68.0
    padding: 2.0
    line_color: "white"
    line_width: 2
    num_stripes: 20
    light_color: "#6da942"
    dark_color: "#507d2a"
  
  # Player and ball settings
  players:
    show: true
    home_color: "blue"
    away_color: "red"
    radius: 1.0
    show_jersey_numbers: true
    jersey_font_size: 8
  
  ball:
    show: true
    color: "black"
    radius: 0.7
  
  # Trail settings
  trails:
    show: true
    length: 5
    player_alpha: 0.5
    ball_alpha: 0.5
    player_width: 1.5
    ball_width: 1.0

# Graph settings 
graph:
  enabled: true
  type: "none"  # Current graph type
  
  # Graph-specific parameters
  ball_knn:
    k: 8
  
  ball_radius:
    radius: 20.0
  
  knn_spatial:
    k: 8
  
  radius_spatial:
    radius: 20.0
  
  knn_full:
    k: 8
  
  radius_full:
    radius: 20.0
  
  tactical:
    # No specific parameters needed
  
  none:
    # No parameters
  
  fc:
    # No parameters
  
  # Edge visualization
  edges:
    home_team_color: "blue"
    away_team_color: "red"
    ball_connection_color: "black"
    line_width: 1.0
    alpha: 0.5
  
  # Legend
  show_legend: true
  legend_position: "upper left"

# Animation settings
animation:
  create: true
  fps: 5
  interval: 200
  dpi: 100
  format: "gif"

# Output settings
output:
  save_frames: false
  frame_format: "png"
  filename_pattern: "{graph_type}_{event_type}_{game_time}_{timestamp}"